sudo: false
language: python
python:
    - "2.7"
    - "3.6"
    # - "3.7"
matrix:
    include:
        - { python: 3.6, env: TOXENV=flake8 }
        - { python: 3.6, env: TOXENV=isort }
        # - { python: 3.7, dist: xenial, sudo: true }

install:
    - pip install tox-travis
    - pip install coveralls
script: tox
after_success: if [ -e .coverage ]; then coveralls; fi
